let boardData= {
	"BoardVersion": 0,
	"IsBetsAllowed": false,
	"IsBoardDisabled": false,
	"IsFinnished": false,
	"IsGameFinished": false,
	"IsGameStarted": false,
	"IsObserver": false,
	"JackpotAmount": 55.9846,
	"Last100SpinNumbers": {
			0: {"Number": 20, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69194},
			1: {"Number": 15, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69192},
			2: {"Number": 21, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69190},
			3: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69188},
			4: {"Number": 34, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69186},
			5: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69184},
			6: {"Number": 17, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69182},
			7: {"Number": 25, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69180},
			8: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69177},
			9: {"Number": 13, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69175},
			10: {"Number": 14, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69173},
			11: {"Number": 11, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69170},
			12: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69168},
			13: {"Number": 5, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69165},
			14: {"Number": 25, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69163},
			15: {"Number": 24, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69160},
			16: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69157},
			17: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69154},
			18: {"Number": 10, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69151},
			19: {"Number": 16, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69149},
			20: {"Number": 10, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69147},
			21: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69145},
			22: {"Number": 11, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69143},
			23: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69141},
			24: {"Number": 25, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69139},
			25: {"Number": 24, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69137},
			26: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69135},
			27: {"Number": 32, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69133},
			28: {"Number": 17, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69131},
			29: {"Number": 17, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69129},
			30: {"Number": 26, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69127},
			31: {"Number": 29, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69124},
			32: {"Number": 5, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69122},
			33: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69119},
			34: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69117},
			35: {"Number": 30, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69116},
			36: {"Number": 34, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69114},
			37: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69112},
			38: {"Number": 23, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69110},
			39: {"Number": 26, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69108},
			40: {"Number": 29, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69106},
			41: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69103},
			42: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69101},
			43: {"Number": 31, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69098},
			44: {"Number": 25, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69096},
			45: {"Number": 36, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69094},
			46: {"Number": 5, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69092},
			47: {"Number": 20, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69089},
			48: {"Number": 30, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69087},
			49: {"Number": 18, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69085},
			50: {"Number": 32, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69083},
			51: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69081},
			52: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69079},
			53: {"Number": 5, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69077},
			54: {"Number": 15, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69075},
			55: {"Number": 23, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69073},
			56: {"Number": 13, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69070},
			57: {"Number": 16, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69068},
			58: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69066},
			59: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69064},
			60: {"Number": 0, "Color": "Green", "IsEven": null, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69062},
			61: {"Number": 30, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69060},
			62: {"Number": 13, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69058},
			63: {"Number": 31, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69056},
			64: {"Number": 22, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69054},
			65: {"Number": 18, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69052},
			66: {"Number": 24, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69050},
			67: {"Number": 13, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69047},
			68: {"Number": 14, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69045},
			69: {"Number": 18, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69043},
			70: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69041},
			71: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69039},
			72: {"Number": 27, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69037},
			73: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69035},
			74: {"Number": 36, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69033},
			75: {"Number": 30, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69031},
			76: {"Number": 13, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69029},
			77: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69027},
			78: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69025},
			79: {"Number": 26, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69022},
			80: {"Number": 20, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69020},
			81: {"Number": 2, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69018},
			82: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69016},
			83: {"Number": 19, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69014},
			84: {"Number": 21, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69012},
			85: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69010},
			86: {"Number": 18, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69008},
			87: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69006},
			88: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69004},
			89: {"Number": 29, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 69002},
			90: {"Number": 26, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68999},
			91: {"Number": 22, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68997},
			92: {"Number": 12, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68995},
			93: {"Number": 19, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68993},
			94: {"Number": 22, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68991},
			95: {"Number": 28, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68989},
			96: {"Number": 11, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68987},
			97: {"Number": 20, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68985},
			98: {"Number": 29, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68983},
			99: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 68981}
	},
	"LuckyNumber": null,
	"LuckyWinningNumber": null,
	"OnlinePlayers": 2,
	"Options": [],
	"PlayerInfo":{
		"AllowRebet": false,
		"AvailableAmount": 76060.49,
		"BetAmount": 0.01,
		"CompleteBet": false,
		"Currency":{
			"CurrencyCode": "GEL",
			"FractionDigit": 2,
			
		},
		"DisplayName": "sofio",
		"FinalBet": false,
		"IsDisabled": false,
		"IsZeroSubReturn": false,
		"JackpotThrowAmount": null,
		"JackpotThrowAmountPerPlayer": null,
		"LatestSpins":{
			0: {"SpinNumber": 63540, "BetAmount": 8, "WonAmount": 12, "SpinDate": "2019/11/24 10:21:57"},
			1: {"SpinNumber": 63539, "BetAmount": 8, "WonAmount": 12, "SpinDate": "2019/11/24 10:21:15"},
			2: {"SpinNumber": 63537, "BetAmount": 1, "WonAmount": 2, "SpinDate": "2019/11/24 10:18:08"},
			3: {"SpinNumber": 63214, "BetAmount": 0.05, "WonAmount": 1.8, "SpinDate": "2019/11/22 11:55:03"},
			4: {"SpinNumber": 57999, "BetAmount": 2.5, "WonAmount": 0, "SpinDate": "2019/11/19 07:46:59"},
			5: {"SpinNumber": 56719, "BetAmount": 5.5, "WonAmount": 0, "SpinDate": "2019/11/18 08:44:02"},
			6: {"SpinNumber": 56689, "BetAmount": 80, "WonAmount": 360, "SpinDate": "2019/11/18 08:31:23"},
			7: {"SpinNumber": 56681, "BetAmount": 60, "WonAmount": 0, "SpinDate": "2019/11/18 08:27:53"},
			8: {"SpinNumber": 56679, "BetAmount": 60, "WonAmount": 360, "SpinDate": "2019/11/18 08:27:08"},
			9: {"SpinNumber": 56668, "BetAmount": 80, "WonAmount": 360, "SpinDate": "2019/11/18 08:21:42"},
			10: {"SpinNumber": 56662, "BetAmount": 10, "WonAmount": 0, "SpinDate": "2019/11/18 08:19:51"}
		},
		"NeighboursLength": 2,
		"PlacedAmount": 0,
		"PlacedBets": [
		  {
		    "Multiplier": 5,
		    "BetName": "Straight up 11"
		  },
		  {
		    "Multiplier": 5,
		    "BetName": "Straight up 14"
		  },
		  {
		    "Multiplier": 5,
		    "BetName": "Straight up 13"
		  }
		],
		"SelectedMultiplier": 5,
		"WonAmount": 0,
		"PlayerKey": "1ae73f95-417d-417d-b7ac-5e113731969f",
		"ProgressPercent": 0,
		"ProgressTime": 0,
		"SpinNumber": 69024
	},
		"SpinsDistributionPercents": {
  "Red": 69,
  "ZeroRB": 6,
  "Black": 25,
  "Even": 44,
  "ZeroEO": 6,
  "Odd": 56,
  "St1": 41,
  "Nd2": 31,
  "Rd3": 28,
  "FirstHalf": 62,
  "SecondHalf": 38,
  "NumberStats": [
    2,
    1,
    0,
    2,
    0,
    1,
    0,
    0,
    0,
    5,
    1,
    0,
    3,
    1,
    2,
    1,
    2,
    1,
    0,
    0,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    2,
    1,
    1,
    0,
    1,
    0,
    0,
    0,
    1
  ],
  "HotNumbers": [
    {
      "Number": 9,
      "Color": 0,
      "IsEven": false
    },
    {
      "Number": 12,
      "Color": 0,
      "IsEven": true
    },
    {
      "Number": 28,
      "Color": 1,
      "IsEven": true
    },
    {
      "Number": 16,
      "Color": 0,
      "IsEven": true
    },
    {
      "Number": 14,
      "Color": 0,
      "IsEven": true
    }
  ],
  "ColdNumbers": [
    {
      "Number": 2,
      "Color": 1,
      "IsEven": true
    },
    {
      "Number": 4,
      "Color": 1,
      "IsEven": true
    },
    {
      "Number": 6,
      "Color": 1,
      "IsEven": true
    },
    {
      "Number": 7,
      "Color": 0,
      "IsEven": false
    },
    {
      "Number": 8,
      "Color": 1,
      "IsEven": true
    }
  ]
},
		"NumberStats": {
			"Odd": 0,
			"Rd3": 0,
			"Red": 0,
			"SecondHalf": 0,
			"St1": 0,
			"ZeroEO": 0,
			"ZeroRB": 0
	},
	"WinningNumber": null,
}


